# Generated by Django 3.2.dev20200824123207 on 2020-09-29 22:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(default='', max_length=300)),
                ('foto', models.ImageField(upload_to='images/')),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=15)),
                ('report', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('fechavence', models.DateField(default=datetime.date(2020, 10, 6))),
                ('edad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appMascotas.edad')),
                ('especie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appMascotas.especie')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appMascotas.estado')),
                ('localidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appMascotas.localidad')),
                ('sexo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appMascotas.sexo')),
            ],
        ),
    ]
