# Generated by Django 3.2.dev20200824123207 on 2020-09-30 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.date(2020, 9, 30)),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fechavence',
            field=models.DateField(default=datetime.date(2020, 10, 7)),
        ),
    ]
